const app = document.querySelector('[data-app]')
const intro = document.querySelector('[data-intro]')
const game = document.querySelector('[data-game]')
const stage = document.querySelector('[data-stage]')
const targets = document.querySelectorAll('[data-target]')
const player = document.querySelector('[data-player]')
const clone = document.querySelector('[data-clone]')
const finish = document.querySelector('[data-finish]')
const playButtons = document.querySelectorAll('[data-play-button]')
const control = document.querySelector('[data-control]')
const controlThumb = document.querySelector('[data-control-thumb]')
const livesElement = document.querySelector('[data-lives]')
const meterElement = document.querySelector('[data-meter]')

export { app, intro, game, stage, targets, player, clone, finish, playButtons, control, controlThumb, livesElement, meterElement }
